### ISSUE TITLE
hello，我是diffusion watermark的collaborator，我想要知道您的信息

### ISSUE THREAD

**Issue by zzk2021** [yuhan19971211/Design-of-Tunable-Microwave-Photon-Filter#1]
在此之前，我不敢发布任何代码以免泄露。

**Comment by hexiaomo624** [comment]
你想了解的具体信息是什么呢？

**Comment by zzk2021** [comment]
> 你想了解的具体信息是什么呢？

您好，我想要知道您对这个项目的预期是？其次我想知道您在其中的参与度

**Comment by hexiaomo624** [comment]
你的另一位同学没有跟你沟通吗？我是指导，我肯定是需要全程参与的，如果实在太担心也可以不选择共享给我代码，我们以别的方式沟通也是ok的
